### ISSUE TITLE
Fixed C Drive

### ISSUE THREAD

**Issue by elysoto** [JonSn0w/PlayMusic#11]
Styles.inc is using a fixed C: drive

Replace with

AppPath="%HOMEDRIVE%%HOMEPATH%...
PlaybackPath="%HOMEDRIVE%%HOMEPATH%...
DesktopSettingsPath="%HOMEDRIVE%%HOMEPATH%...

**Comment by tterb** [comment]
Okay, will do.

**Comment by tterb** [comment]
✔️ Fixed with commit 007ff6dd58bc07a3ac5f1e18e533fc91e6c6037e
