### ISSUE TITLE
Remove auth skin

### ISSUE THREAD

**Issue by tjhrulz** [JonSn0w/PlayMusic#12]
I didn't know you had updated your skin to use my plugin. Just so you know as of GPMDP Plugin 1.3 the authentication and settings changes are now automatic so you should no longer have to handle that. Also I don't see what version of the plugin you are using in your skin but the latest version is 1.3.2 and fixes a handful of potential issues.

**Comment by tterb** [comment]
I haven't published a release with the plugin integrations yet, so I'll just update the plugin and make a note of the changes and updated version in the docs. 
Thanks for the heads up!

**Comment by tjhrulz** [comment]
No problem just saw that you were using the auth skin and I have been trying to find people who use it to tell them they no longer need it.
