### ISSUE TITLE
2bit-text are garbled.

### ISSUE THREAD

**Issue by himamama** [JonSn0w/PlayMusic#18]
Texts Japanese or other 2bit texts are full of garble.
Maybe component file's encode problem?

**Comment by tterb** [comment]
I'll try to recreate this issue and see if I can find the source.

**Comment by tterb** [comment]
I'm having some trouble recreating this issue, would it be possible to provide screenshots and/or the information that the skin is attempting to display when the issue occurs?

**Comment by himamama** [comment]
Thank you for your response.
I checked out my download files. Then I found that files are old vesion.(I was download from divinart)
New version is working without any problems. Sorry a lot for the trouble.
