### ISSUE TITLE
A few bugs in 1.2.0

### ISSUE THREAD

**Issue by ghost** [JonSn0w/PlayMusic#7]
Hi, at first: Thanks for this awesome Update. The Visualizer is great!!

But it seems like a few bugs got into the Release (I only tested the Landscape Variant):

1. The Overflow Button opening the Settings is gone.
2. Shuffle & Repeat Buttons are gone.
3. When opening the Settings Menu via Rainmeter it's missing its Background.
4. While the Google Play Music Player is closed the Skin completely disappears instead of showing the Icon. This might be due to a Setting but I can't access the Settings Menu and I really don't want to wade through the whole source to find this specific setting (if it even exists).

Maybe I'm missing a new way to access all of these but I don't think so.

Again: Thanks for your great work! :)

Edit: If you want to I'll create separate issues for the 4 points but I didn't want to spam you with issues.

**Comment by tterb** [comment]
Thanks for the feedback and I'm glad you enjoy the changes! 
I'll review these issues and see if I can get them straightened out over the next couple days.
Also, the way you have submitted the issue is better than four separate issues, as they seem to share a common theme. Though, if one issue turns out to be more complicated than the others, I will designate it to a separate issue.

**Comment by tterb** [comment]
After reviewing the files, it seems that all the necessary image files should be included in the *.rmskin* file.
In order to diagnose the source of the issue, could you confirm that these files are in your ```Ranmeter\Skins\PlayMusic\@Resources\Image``` folder:
  * PlayMusic_Menu.png
  * shuffle.png
  * repeat.png
  * dots.png

**Comment by ghost** [comment]
Thanks for the prompt reply!

You're right! I'm missing the Image Folder inside the Skin. I also checked the Rainmeter Log (Didn't even know about this. I'm still really new to Rainmeter.) and I get constant errors about the missing Images (The Skin is also looking for an /images/ and not an /Image/ Folder but I guess you just had a spelling error in there). So that's definitely the source of the bug.

Just so you know: I had already reinstalled the Skin (removed the whole PlayMusic Folder from the Skins folder and then ran the .rmskin file again) before submitting the Bug Report. So reinstalling probably won't fix the issue for me.

**Comment by tterb** [comment]
After doing some further testing, I believe the problem may be with the original _.rmskin_ file used to install the skin. I have replaced it with a new _.rmskin_ file that I have confirmed to work, so I would recommend trying to reinstall the skin using the new installer.
Let me know if you have any problems with the new installer.

**Comment by ghost** [comment]
It's working fine now. Thanks again! :)

**Comment by ghost** [comment]
Should've closed this with the last comment.

**Comment by tterb** [comment]
I'm glad everything's straightened out, I really appreciate you letting me know about the issue.
