### ISSUE TITLE
Few things that could be "improved"

### ISSUE THREAD

**Issue by Alipoodle** [JonSn0w/PlayMusic#8]
I appreciate all of the feedback and taking the time to provide example images, so I'm going to do my best to address each of these points and make sure that we get these issues cleared up.  
I'll check them off here as they are resolved within the repository, though changes won't be present in the *.rmskin* package until the new release is published. 
_______________________________  

# **Circle**
- [x] As you can see on the right side there's a lot of padding, which can be annoying to those people who leave ``Snap to Edges`` on in Rainmeter.    - **Fixed with commit** eeb512a1fb61f440792aaa87b5c97380d52069a1

  * **The padding that is present on the right side is due to the difference in width of the each of the variants and allows the icon to remain in the same place when the skin is in a minimized state (when GPMDP is closed) - A solution to this may be to have a setting to set the alignment of the skin to left or right(*current*) depending on which side of the screen the user chooses to place it on.**
<br>

- [x] You can also see that the right side and at the bottom is slightly cut off when someone isn't hovering over the skin. 

  * **I am unsure what could be causing the bottom to be cut off, so I will do some further investigating there.**

# **Square**
- [x] Again with the padding with the people who use ``Snap to Edges``  - **Fixed with commit** eeb512a1fb61f440792aaa87b5c97380d52069a1

  * **Same as above**
<br>

- [x] Also when you have a long Album, Artist or Track name that it comes off - **Fixed with commit** 99767e6d7c6b96548de46bba572236dfcec07fda

  * **This should be a quick fix, so I'll make sure to check the clipping and available text width on the square variant.**
<br>

# **Land Scape**
- [x] The Visualizer is also a tad bit too low and clips onto the Progress bar - **Fixed with commit** 99767e6d7c6b96548de46bba572236dfcec07fda

  * **This is also pretty easy to fix, so I'll make sure to make these adjustments** 
<br>

# **Overall**
- [x] When you just refresh it you seem to get (at least for me) a ``20`` and a White bar somewhere. (This might be possible to explain)

  *  **The bar and the "20" you are seeing is intended to be your current volume. If you hover your cursor over the skin and the move it, it should go away.**
<br>

- [x] The Shuffle Seemed to show up when I refresh the skin, however disappears after about a second. 

  * **If I understand correctly, this is the expected behavior when the Shuffle feature isn't enabled in GPMDP, and its brief presence is presumably the result of the script collecting the data from the application. Though, I will do some further testing to see if there is a way to improve on this process.**
<br>

- [x] The Scroll feature didn't seem to work. (Again another one of these cool features and must have been hard to make - **Fixed with commit** 03921478b8132e223abaddc8f635315f8f27d2a0

  * **I've done a bit of experimenting and found that Rainmeter doesn't always recognize scrolling via a trackpad. Though, if you are using a mouse and scroll the scroll-wheel up or down while your cursor over the skin, you should see the aforementioned bar and number appear and increase or decrease depending on the direction you scroll. If this is not the case, let me know and I will investigate further into whether its an issue with a plugin or my implementations.**  
<br>

- [x] Colors can also easily be broken from changing to quickly - **Fixed with commit** affb81ed918909938ebfd1eeff783c0ff14a3696
- [x] The Skin only seems to auto Refresh from changing settings when changing colours... this would be nice to change when you change all settings.  - **The auto-update processes have been addressed across multiple commits** 

  * **I believe both of these are issues are a result of the way the settings are currently being handled and maintained across all three variants, as well as the settings-menu. I will try to experiment more with ways to allow changing the settings to be more responsive.**

___________________________________  

Please let me know if I misunderstood or you need clarification on any of these points, so we can get them resolved.

**Comment by tterb** [comment]
I apologize for modifying your original post, this was meant to be posted as a comment, but it seems it instead edited the original post... I guess that's what I get for trying to respond via smartphone.
I'll do my best to clean it up again once I'm at my computer.

**Comment by Alipoodle** [comment]
Yes, you seemed to understand it all 👍

**Comment by tterb** [comment]
I have a few questions to help me troubleshoot these issues:
  * Are you having the issue with the scrollwheel volume control functionality when using a mouse?
  * Does the Shuffle icon show up correctly when the shuffle feature is enabled in GPMDP?
  * I am also having a hard time replicating this issue you presented with the Circle variant:  
    - [ ] *You can also see that the right side and at the bottom is slightly cut off when someone isn't hovering over the skin.*

Can you think of any settings or configurations that could have an impact on my ability to replicate this issue?

**Comment by Alipoodle** [comment]
- The issue with using the scroll was on my laptop... However i was using a mouse at the time. (Worked fine on desktop.) Haven't been able to retest since.
- The Shuffle icon worked correctly after doing a Shuffle of all my Songs, although didn't work when playing something like Last Added.
Did another test... and after doing a refresh of the skin the shuffle showed up... so might be a one time bug... I'll do some more test on it later.
- I was using the Large sized, that's all i can think, as the smaller one isn't effected by this.

**Comment by tterb** [comment]
* The scrolling feature is currently working using a mouse with the laptop that I'm writing this on, though I'm interested to hear the results if you test the functionality again to see if maybe it varies by mouse manufacturer.
  * I'll check this one off for now, though let me know if the problem arises again and I will investigate further.
  * I still haven't been able to recreate this issue yet, though I'm making some changes that I suspect could have contributed to this issue.

**Comment by Alipoodle** [comment]
Towards the scrolling... both on Desktop and Laptop, It seems to be struggling...

- Laptop Seems to not want to move at all
- Desktop only seems work after a refresh, and the first hover. Once i move of the Skin again... the feature goes and have to refresh to see again.

**Comment by tterb** [comment]
Okay, I've been working through methods of stabilizing the performance of this functionality, as well as the skins update processes.  
I will keep this issue updated with the progress.
